version: '3.8'

services:
  app:
    container_name: node_firebase_dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4000:4000"
      - "8080:8080"
      - "8085:8085"
      - "5001:5001"
      - "9000:9000"
      - "9099:9099"
      - "9199:9199"
    environment:
      - NODE_ENV=development
    command: npm run start:dev
